In [1]:
%matplotlib inline

# Tensors 
==========================

**Tensors是一种特殊的数据结构,与数组和矩阵非常相似.
在PyTorch中,我们使用Tensors来编码模型的输入和输出,以及模型的参数.
Tensors类似于 `NumPy <https://numpy.org/>` ,除了Tensors可以在gpu或其他硬件加速器上运行.**

**事实上,Tensors和NumPy数组通常可以共享相同的底层内存,从而不需要复制数据(参见“bridge-to-np-label”).
Tensors也为自动区分进行了优化(我们将在后面的`Autograd <autograd_tutorial.html>`部分).**

In [2]:
import torch
import numpy as np

## 初始化一个Tensor

Tensors 可以通过各种方式进行初始化.看下接下来的例子：

### **直接从data中初始化**

Tensors可以直接从data中创建。数据类型是自动推断的。



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### **从一个NumPy array中初始化**

Tensors 可以从 NumPy arrays中初始化 (and vice versa - see `bridge-to-np-label`).



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### **从另外一个tensor:**

**新张量保留参数张量的属性(形状，数据类型)，除非显式重写。**



In [5]:
x_ones = torch.ones_like(x_data) # 保留x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖x_data的数据类型
# torch.rand_like 's function:
#   Returns a tensor with the same size as input that is filled with random numbers from a uniform distribution on the interval [0, 1). 
#   torch.rand_like(input) is equivalent to torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device).
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9123, 0.3356],
        [0.7454, 0.5176]]) 



### **用随机值或常数值初始化:**

``shape`` 是一个张量维度的元组。在下面的函数中，它决定了输出张量的维数。



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1795, 0.1913, 0.8608],
        [0.9474, 0.6672, 0.2368]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## Tensor 的一些属性

Tensor 的属性描述了他们的shape,数据的类型,以及他们存储在哪个装置上(cpu or gpu).


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## Tensors 上的操作

> Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, 
indexing, slicing), sampling and more are
comprehensively described `here <https://pytorch.org/docs/stable/torch.html>`__.

> Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

> By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using 
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [9]:
# 如果GPU存在的话将我们的tensor转移至GPU
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**尝试列表中的一些操作.**

**标准的 numpy-like 索引和切片:**

In [10]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### **连接张量**
可以使用``torch.cat``将给定维数的张量序列连接起来。
参见`torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,另一个连接张量的操作和``torch.cat``有微妙的不同。

##### **torch.cat:** 
Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.
> torch.cat(tensors, dim=0, *, out=None) → Tensor
- tensors (sequence of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.(任何相同类型张量的python序列.提供的非空张量必须具有相同的形状,除了在cat维度.)
- dim (int, optional) – the dimension over which the tensors are concatenated (张量连接的维数.)

------------------

##### **torch.stack:** 
Concatenates a sequence of tensors along a new dimension. All tensors need to be of the same size.
> torch.stack(tensors, dim=0, *, out=None) → Tensor
- tensors (sequence of Tensors) – sequence of tensors to concatenate(要连接的张量序列.)
- dim (int) – dimension to insert. Has to be between 0 and the number of dimensions of concatenated tensors (inclusive) (插入的维度.必须在0和级联张量的维数之间(包括))


In [20]:
t1_0 = torch.cat([tensor, tensor, tensor], dim=0)
t1_1 = torch.cat([tensor, tensor, tensor], dim=1)
# t1_2 = torch.cat([tensor, tensor, tensor], dim=2) # IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
print(t1_0,'\n',t1_1)
t2_0 = torch.stack([tensor, tensor, tensor], dim=0)
t2_1 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2_0,'\n',t2_1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]]) 
 tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [

### **算术运算**



In [23]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# 这是计算两个张量之间的矩阵乘法
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(tensor, '\n', y1,'\n', y2,'\n', y3,'\n')

# This computes the element-wise product. z1, z2, z3 will have the same value
# 这是计算元素的乘积
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(tensor, '\n', z1, '\n', z2,'\n', z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### **单元素张量** 
如果你有一个单元素张量，例如通过聚集所有张量
把一个张量的值转换成一个值，可以使用 ``item()``把它转换成Python数值:


In [25]:
agg = tensor.sum() # Returns the sum of all elements in the input tensor.
agg_item = agg.item()  
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


### **就地操作**
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix. 
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [30]:
print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")
random_data = torch.rand_like(tensor)
tensor.copy_(random_data)
print(random_data, "\n", tensor)

tensor([[0.2604, 0.2796, 0.5094, 0.0687],
        [0.2978, 0.4229, 0.3648, 0.1990],
        [0.5823, 0.9985, 0.1751, 0.3498],
        [0.8418, 0.9451, 0.1670, 0.0736]]) 

tensor([[5.2604, 5.2796, 5.5094, 5.0687],
        [5.2978, 5.4229, 5.3648, 5.1990],
        [5.5823, 5.9985, 5.1751, 5.3498],
        [5.8418, 5.9451, 5.1670, 5.0736]]) 

tensor([[0.5956, 0.0731, 0.7831, 0.0896],
        [0.4536, 0.8038, 0.9504, 0.5316],
        [0.8082, 0.9876, 0.4477, 0.3678],
        [0.0701, 0.0245, 0.5533, 0.3587]]) 
 tensor([[0.5956, 0.0731, 0.7831, 0.0896],
        [0.4536, 0.8038, 0.9504, 0.5316],
        [0.8082, 0.9876, 0.4477, 0.3678],
        [0.0701, 0.0245, 0.5533, 0.3587]])


#### **Note**
**就地操作可以节省一些内存,但在计算导数时可能会出现问题,因为会立即造成损失的历史.因此,不鼓励使用它们.**



--------------





## Bridge with NumPy
> Tensors on the CPU and NumPy arrays can share their underlying memory 
locations, and changing one will change	the other. 
(CPU和NumPy数组上的张量可以共享它们的底层内存地点，改变一个就会改变另一个。)



Tensor to NumPy array



In [31]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [32]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor



In [33]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [34]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
